### ISSUE TITLE
16 line value

### ISSUE THREAD

**Issue by ginsep** [sarunas-zilinskas/docker-compose-macvlan#3]
https://github.com/sarunas-zilinskas/docker-compose-macvlan/blob/d975947e05f374a16e1f9ddbeea74d4e076c988e/docker-compose.yml#L16
It should be value **dockervlan**?

**Comment by sarunas-zilinskas** [comment]
Absolutely yes! This is my bad, I made a typo. Thank you for your attention to details and pointing this out!
